# Google rejects sameAs URIs unless they are type schema:URL"

######  DEPRECATED - DO NOT USE!
# Issue in NoteBook 11 - page 3 - schema:sameAs should always be a literal.  
# It is semantically wrong to assign a type URL to a Person, or other type of entity.

PREFIX schema: <http://schema.org/>                
delete { 
  ?uri schema:sameAs ?sameAs
}
insert {
  ?uri schema:sameAs ?sameAsUri .  ?sameAsUri a schema:URL   
}
where { 
  ?uri a schema:Place ; 
    schema:sameAs ?sameAs . 
  bind (URI(?sameAs) as  ?sameAsUri) 
  filter(!isURI(?sameAs))   
}