SELECT * WHERE {
  VALUES ?job {
    wd:Q33999  # actors
    wd:Q3387717 # theatrical director
    wd:Q639669 # musician
  }
  ?person wdt:P106 ?job;
    wdt:P27 wd:Q16;
    wdt:P569 ?birth;
    rdfs:label ?name.
  BIND((NOW()) - ?birth AS ?days)
  FILTER(?days < (365  * 80 )) # born less than 80 years ago
  FILTER((LANG(?name)) = "en")
  OPTIONAL {
    ?person rdfs:label ?name_fr.
    FILTER((LANG(?name_fr)) = "fr")
  }
}