
# In Wikidata there are (296) actors and stage directors that are born in Canada but not documented as Canadian Citizens. 
# Created by Frédéric Julien - JUNE 2020

SELECT ?person  ?personLabel 
WHERE
{
  values ?job {wd:Q33999 wd:Q3387717}   #actors and stage directors
  ?person wdt:P106 ?job ;     #has a job from the listed values
    wdt:P31  wd:Q5 ;      #human
    wdt:P19/wdt:P131+ wd:Q16 . #place of birth in located in Canada

  filter(not exists { ?person wdt:P27 wd:Q16 .} )  #country of citizenship Canada
  
SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
} order by ?personLabel




