SELECT DISTINCT ?item ?itemLabel  ?provinceLabel
WHERE {
   ?item wdt:P31 wd:Q43229 . # find organizations
   ?item wdt:P17 wd:Q16.  # in Canada
   ?item wdt:P101/wdt:P279* wd:Q184485 . # with field of work performing arts or subclass
  
   OPTIONAL { ?item wdt:P276*/wdt:P131* ?province  .  }  # location or administrative entity, or location followed by administrative entity
   FILTER (?province = ?p)
  
   { select ?p where { ?p wdt:P31 wd:Q11828004.}}  # get the list of provinces (TODO: add territories)

   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}