PREFIX schema: <http://schema.org/> 

insert data { 
  graph <graph_name_placeholder> {
    <uri_placeholder> a schema:Person ;
      schema:additionalType "additional_type_placeholder";
      schema:name "name_placeholder"; 
      schema:description  "description_placeholder"  ; 
      schema:image  "image_placeholder"   ; 
      schema:address  "address_placeholder" ; 
      schema:url  "official_website_placeholder"  ;
      schema:hasOccupation  "has_occupation_placeholder" ; 
      schema:mainEntityOfPage <crawled_webpage_placeholder#WebPage> .
    <crawled_webpage_placeholder#WebPage> a schema:WebPage  ;
      schema:url  "crawled_webpage_placeholder" .
  }
}
