PREFIX schema: <http://schema.org/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX adr: <http://kg.artsdata.ca/resource/>
PREFIX capacoa: <https://capacoa.ca/vocabulary#>

insert data { 
  graph <graph_name_placeholder> {
    <uri_placeholder> a schema:schema_type_placeholder ;
      schema:name "operating_name1_placeholder"@oa ;
      schema:name "operating_name2_placeholder"@ob ;
      schema:name "name_placeholder" ;
      schema:legalName "legal_name_placeholder"@la ;
      schema:alternateName "also_known_as_placeholder" ;
      wdt:P8860 "business_number_placeholder" ;
      schema:additionalType capacoa:LegalForm_legal_form_uri ;
      schema:additionalType capacoa:CharitableStatus_charitable_status_uri ; 
      schema:additionalType capacoa:PrimaryActivity_primary_activity_uri ;
      schema:additionalType capacoa:PresentingFormat_presenting_format_uri ;
      schema:additionalType capacoa:MemberType_member_type_placeholder ;
      schema:url "website_official_placeholder" ;
      schema:url [ a schema:Role ; 
                  schema:roleName "Events Webpage" ;
                  schema:url "events_page_placeholder" ] ;
      schema:additionalType capacoa:TermsConditions_terms_conditions_v1_0_uri ;
      schema:address [
        a schema:PostalAddress ;
        schema:addressCountry "pmpro_bcountry_placeholder" ;
        schema:addressLocality "pmpro_bcity_placeholder" ;
        schema:addressRegion "pmpro_bstate_placeholder" 
      ] ;
      schema:identifier "wikidata_id_placeholder" ;
      schema:location [ a schema:Role ; 
                        schema:roleName "venue_relationship_placeholder" ;
                        schema:location [ a schema:Place ; 
                                          schema:name "venue_name_placeholder"@en  ;
                                          schema:identifier "wikidata_id_venue_placeholder" ] ] ;
      schema:location [ a schema:Role ; 
                        schema:roleName "venue_other_relationship_placeholder" ;
                        schema:location [ a schema:Place ; 
                                          schema:name "venue_other_name_placeholder"@en ;
                                          schema:identifier "wikidata_id_venue_other_placeholder" ] ] .
    
    capacoa:LegalForm_legal_form_uri a skos:Concept ; 
      skos:inScheme capacoa:QuestionnaireChoices; 
      skos:hiddenLabel "legal_form_placeholder" .
    capacoa:LegalForm a skos:Collection ;
      skos:member capacoa:LegalForm_legal_form_uri ;
      skos:prefLabel "Legal Form"@en .
    
    capacoa:CharitableStatus_charitable_status_uri a skos:Concept ; 
      skos:inScheme capacoa:QuestionnaireChoices; 
      skos:hiddenLabel  "charitable_status_placeholder" .
    capacoa:CharitableStatus a skos:Collection  ;
       skos:member capacoa:CharitableStatus_charitable_status_uri ;
       skos:prefLabel "Charitable Status"@en .

    capacoa:PrimaryActivity_primary_activity_uri a skos:Concept ; 
      skos:inScheme capacoa:QuestionnaireChoices; 
      skos:hiddenLabel "primary_activity_placeholder" .
    capacoa:PrimaryActivity a skos:Collection  ;
      skos:member capacoa:PrimaryActivity_primary_activity_uri ;
      skos:prefLabel  "Primary Activity of Organization"@en .

    capacoa:MemberType_member_type_placeholder a skos:Concept ; 
      skos:inScheme capacoa:QuestionnaireChoices; 
      skos:hiddenLabel "member_type_placeholder" .
    capacoa:MemberType a skos:Collection  ;
      skos:member capacoa:MemberType_member_placeholder ;
      skos:prefLabel  "Member type: organization, individual(ind), individual lifetime (indlife)"@en .

    capacoa:PresentingFormat_presenting_format_uri a skos:Concept ; 
      skos:inScheme capacoa:QuestionnaireChoices; 
      skos:hiddenLabel "presenting_format_placeholder" .
    capacoa:PresentingFormat a skos:Collection  ;
       skos:member capacoa:PresentingFormat_presenting_format_uri ;
        skos:prefLabel "If a presenting organization, how are your arts presenting activities organized?"@en .

    capacoa:TermsConditions_terms_conditions_v1_0_uri a skos:Concept ; 
      skos:inScheme capacoa:QuestionnaireChoices; 
      skos:hiddenLabel "terms_conditions_v1_0_placeholder" .
    capacoa:TermsConditionsV1_0 a skos:Collection  ;
      skos:member capacoa:TermsConditions_terms_conditions_v1_0_uri ;
      skos:prefLabel "Open Data Strategy Consent Options"@en ;
      skos:definition capacoa:TermsConditionsV1_0_document .

    capacoa:TermsConditionsV1_0_document a schema:CreativeWork ;
      schema:name "CAPACOA Membership Open Data Strategy (version 1.0)"@en ;
      schema:url "https://capacoa.ca/en/membership/open-data-strategy-version-1-0/" . 

    capacoa:MembershipQuestionnaire a skos:ConceptScheme .

    capacoa:MembershipQuestionnaireCollection a skos:Collection ;
      skos:member capacoa:TermsConditionsV1_0 ;
      skos:member capacoa:PresentingFormat ;
      skos:member capacoa:PrimaryActivity ;
      skos:member capacoa:CharitableStatus ;
      skos:member capacoa:LegalForm ;
      skos:prefLabel "CAPACOA Membership Questionnaire"@en .
  }
}
