PREFIX schema: <http://schema.org/> 
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

insert { 
  graph <graph_name_placeholder> {
    <uri_placeholder>  wdt:P172 "additional_type_placeholder";
      schema:name "name_placeholder"; 
      schema:description  "description_placeholder"  ; 
      schema:image  "image_placeholder"   ; 
      schema:workLocation  "address_placeholder" ; 
      schema:url  "official_website_placeholder"  ;
      schema:hasOccupation  "has_occupation_placeholder" ; 
      schema:mainEntityOfPage <crawled_webpage_placeholder#WebPage> .
    <crawled_webpage_placeholder#WebPage> a schema:WebPage  ;
      schema:url  "crawled_webpage_placeholder" ;
      schema:inLanguage "en" ;
      schema:lastReviewed ?date .
    }
}
where {
      BIND(NOW() as ?date)
}
