PREFIX schema: <http://schema.org/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX adr: <http://kg.artsdata.ca/resource/>

insert data { 
  graph <graph_name_placeholder> {
    <uri_placeholder> a schema:Organization ;
      schema:name "name_placeholder"@fr ;
      schema:location "location-1-id", "location-2-id", "location-3-id", "location-4-id" .
  }
}
