PREFIX schema: <http://schema.org/>

delete {
     graph ?g {
        ?s schema:jobTitle ?type }
}
insert {
    graph ?g {
        ?s schema:temp ?category .
        ?s schema:jobTitle ?category_remaining  .
    }
}
#select *
where {
    values ?g {
       <http://uda.ca>
    }
    graph ?g {
        ?s schema:jobTitle ?type .
        filter (contains(?type,")  ")) 
        bind(lcase(concat(STRBEFORE(?type,")"),")")) as ?category )
        bind(STRAFTER(?type,")  " ) as ?category_remaining )
    }
}

# Run this SPARQL multiple times to split long lists - 10 times