PREFIX schema: <http://schema.org/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

insert data { 
  graph <graph_name> {
    <uri> a schema:Event ;
      schema:name "{{name}}"; 
      schema:startDate "{{startDate}}"^^xsd:dateTime ; 
      schema:description  "{{description}}"  ; 
      schema:image  "{{image}}"   ; 
      schema:location  "{{location}}" ; 
      schema:url  "{{url}}"  ;
      schema:eventStatus  schema:status .
  }
}
