PREFIX schema: <http://schema.org/>

delete {
 	graph <graph_name_placeholder> {
        ?org schema:memberOf ?adid .
    }
}
insert {
	graph <graph_name_placeholder> {
        ?org schema:memberOf ?adid_uri .
    }
}
where {
    graph <graph_name_placeholder> {
        ?org schema:memberOf ?adid .
        bind(URI(?adid) as ?adid_uri)
    }
}

# Post-processor to make the object of schema:memberOf into a URI
