PREFIX schema: <http://schema.org/>

delete {
 	graph <https://tapa.ca/membership/member-directory> {
        ?org schema:memberOf ?adid .
    }
}
insert {
	graph <https://tapa.ca/membership/member-directory> {
        ?org schema:memberOf ?adid_uri .
    }
}
where {
    graph <https://tapa.ca/membership/member-directory> {
        ?org schema:memberOf ?adid .
        bind(URI(?adid) as ?adid_uri)
    }
}

# Post-processor to make the object of schema:memberOf into a URI
