PREFIX schema: <http://schema.org/>
#select * 
delete {
    graph ?g {
        ?s schema:name ?o .
    }
}
insert {
    graph ?g {
        ?s schema:name ?o_fix .
    }
}
where {
    values ?g {
        <http://kg.artsdata.ca/culture-creates/huginn/rqd>
    }
    graph ?g {
        ?s a schema:Person;
           schema:name ?o .
        filter(contains(?o,"  "))
        bind(replace(?o,"  ", " ") as ?o_fix)
    }
}