PREFIX schema: <http://schema.org/>
# select * 
insert {
    graph  ?g {
        ?p schema:sameAs ?adp 
    }
}
where {
    values ?g {
        <http://kg.artsdata.ca/culture-creates/huginn/rqd>
    }
    graph ?g {
        ?p a schema:Person ;
            schema:name ?name .
        ?adp a schema:Person;
            schema:name ?ad_name .
        filter (str(?name) =  str(?ad_name) )
        filter (?p !=  ?adp )
        filter(!isBlank(?adp))
        filter(!isBlank(?p))
    }  
}