
# causes all resources not currently indexed by <index-name> to get indexed. 
# It is a shorthand way of batching together index updates for several (new) resources.
# https://graphdb.ontotext.com/documentation/9.6/free/full-text-search.html

PREFIX luc: <http://www.ontotext.com/owlim/lucene#>
INSERT DATA { luc:Name luc:updateIndex _:b1 . }