# Update: 29 January 2020  street address (DEPRECATED) (P969) -> located at street address (P6375)

PREFIX schema: <http://schema.org/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT  * 
#FROM   <http://laval.footlight.io> 
WHERE { 
    <http://laval.footlight.io/resource/theatre-marcellin-champagnat> schema:sameAs ?wikidata

   SERVICE <https://query.wikidata.org/sparql>
    { ?wikidata wdt:P6375 ?address ;
           wdt:P856 ?website_url ;
	       wdt:P281 ?postal_code . }
} limit 100  