PREFIX adr: <http://kg.artsdata.ca/resource/> 
PREFIX prov: <http://www.w3.org/ns/prov#> 
PREFIX schema: <http://schema.org/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

insert data { 
  graph <graphUri> { 
    <graphUri>  a prov:Entity ; 
      schema:name "<name>"  ; 
      schema:url "<url>" ; 
      prov:generatedAtTime "<generatedAtTime>"^^xsd:dateTime ;  
      prov:wasAttributedTo <wasAttributedToToolUri> ;     
      prov:wasAttributedTo <wasAttributedToOrgUri> ; 
      prov:wasDerivedFrom <wasDerivedFromUri> ;
      schema:contentRating [  
        a schema:EndorsementRating ;  
        schema:ratingValue 100 ;
        schema:ratingExplanation "Automatic endorsement rating for having provenance metadata"@en ;
        schema:author adr:K1-5 
        ] ;
      <http://creativecommons.org/ns#license> <https://creativecommons.org/publicdomain/mark/1.0> .
  } 
}

# Template used with Huginn servers https://huginn-staging.herokuapp.com/ and https://culture-huginn.herokuapp.com