PREFIX adr: <http://kg.artsdata.ca/resource/> 
PREFIX prov: <http://www.w3.org/ns/prov#> 
PREFIX schema: <http://schema.org/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

insert data { 
  graph {{graphUri}} { 
    {{graphUri}}  a prov:Entity ; 
      schema:name "{{name}}"  ; 
      schema:url "{{url}}" ; 
      prov:generatedAtTime "{{dateTime}}"^^xsd:dateTime ;  
      prov:wasAttributedTo {{wasAttributedToToolUri}} ;     
      prov:wasAttributedTo {{wasAttributedToOrgUri}} ; 
      prov:wasDerivedFrom {{wasDerivedFromUri}} . 
  } 
}