# This SPARQL loads from Wikidata all the entities with an Artsdata ID
# Use to check if there is a mismatch with bidirectional linking
# Note: Some wikidata entities have an owl:sameAs

PREFIX schema: <http://schema.org/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select * 
WHERE { 
   
    bind(URI(concat("http://kg.artsdata.ca/resource/",?adid)) as ?ad_uri)
    OPTIONAL{ ?ad_uri schema:sameAs ?sameAs }
    filter(contains(str(?sameAs),"wikidata.org"))
    filter(?sameAs != str(?wdid))
   SERVICE <https://query.wikidata.org/sparql>
    { 
     
      ?wdid   wdt:P7627   ?adid 
    }

    } 

