# Use this SPARQL after importing data from Wikidata. 
# This SPARQL replaces wdt:P31 with rdf:type (a).
# This is more efficient than setting wdt:P31 owl:equivalentProperty rdf:type because of overal system performance.

PREFIX wdt: <http://www.wikidata.org/prop/direct/>

delete  {   
    graph ?g { ?s wdt:P31 ?o .}
}
insert  {  
    graph ?g { ?s a ?o .}
}
where {  
    graph ?g { ?s wdt:P31 ?o .}
} 