
# SPARQL to add a rank and a maintainer for using Artsdata Rank API.
PREFIX schema: <http://schema.org/>
insert data {
    graph  <http://kg.artsdata.ca/culture-creates/artsdata-planet-ipaa/ipaa-entities> {
          <http://kg.artsdata.ca/culture-creates/artsdata-planet-ipaa/ipaa-entities> schema:contentRating [
            a schema:EndorsementRating ;
            schema:ratingValue 1  ;
            schema:ratingExplanation "Crawled from JSON-LD on ipaa.ca website"
          ] .
           <http://kg.artsdata.ca/culture-creates/artsdata-planet-ipaa/ipaa-entities> schema:maintainer "ipaa.ca"
    }
}