PREFIX schema: <http://schema.org/>
delete {
    graph   <graph_name_placeholder> {
        ?s  schema:hasOccupation ?occ .
    }
}

where { 
  
   graph   <graph_name_placeholder> {
    ?s a schema:Organization ; 
    schema:hasOccupation ?occ .
    filter(str(?occ) = "http://www.wikidata.org/entity/")
   }
} 
