PREFIX schema: <http://schema.org/>
insert data {
    graph <http://wikidata.org/capacoa-members> {
        <http://wikidata.org/capacoa-members>  
            a schema:Dataset ;
            schema:contentRating  <http://wikidata.org/capacoa-members#rating>  ;
            schema:maintainer "wikidata.org" ;
            schema:name "CAPACOA member data from Wikidata"@en ;
            schema:description "Dropped and loaded by Huginn CAPACOA scenario using wikidata-collect-venues.sparql followed by wikidata-set-graph-rating.sparql both in sparql-library."@en .
        <http://wikidata.org/capacoa-members#rating>  
            schema:ratingValue 2 ;
            schema:ratingExplanation "Rated above CAPACOA Membership data to allow members to override social media and other properties in Wikidata."@en .
    }
}