PREFIX schema: <http://schema.org/>
insert {
    graph <graph_name_placeholder> {
        ?s schema:sameAs ?adid .
    }
}
where {
    graph <graph_name_placeholder> {
        ?s schema:sameAs ?isni .
        filter(strstarts(str(?isni),"https://isni"))
    }
    bind(str(?isni) as ?isni_str)
    ?adid schema:sameAs ?isni_str .
    filter(strstarts(str(?adid),"http://kg.artsdata.ca"))
}
