PREFIX schema: <http://schema.org/>
insert {
    graph <graph_name_placeholder> {
        ?s schema:sameAs ?adid .
    }
}
where {
    graph <graph_name_placeholder> {
        ?s schema:sameAs ?isni .
        filter(strstarts(str(?isni),"https://isni"))
    }
    service <http://db.artsdata.ca/repositories/artsdata> 
    {
        ?adid schema:sameAs ?isni .
        filter(strstarts(str(?adid),"http://kg.artsdata.ca"))
    }
}