insert data { 
  graph <http://uda.ca> {
    <{{url}}> schema:firstName "{{firstName  | escape }}"@fr ; 
      schema:lastName "{{lastName  | escape }}"@fr ; 
      schema:jobTitle  "{{expertise  | escape }}"@fr  ; 
      rdfs:comment  "{{description | escape }}"@fr   ; 
      schema:image  "{{image}}" ; 
      schema:photoCredit  "{{photoCredit | escape }}" ; 
      schema:status  "{{memberStatus | escape }}"@fr . 
  }
}
