PREFIX schema: <http://schema.org/> 
insert {
  graph <http://uda.ca> {
    ?s a schema:Person
  } 
} 
where {
  graph <http://uda.ca> {
    ?s schema:lastName ?o
    filter (regex(str(?s), "uda.ca/utilisateurs/"))
  } 
}