# Post-processor to add class schema:Person to all entities with a lastName and the right URI path.
# Note: Do not assign all entites to the Person class because other entities exist (i.e. Provenance.)

PREFIX schema: <http://schema.org/> 

insert {
  graph <http://uda.ca> {
    ?s a schema:Person
  } 
} 
where {
  graph <http://uda.ca> {
    ?s schema:lastName ?o
    filter (regex(str(?s), "uda.ca/utilisateurs/"))
  } 
}