insert data { 
  graph <http://uda.ca> {
    <url_placeholder> schema:firstName "{{firstName}}"@fr ; 
      schema:lastName "{{lastName}}"@fr ; 
      schema:jobTitle  "{{expertise}}"@fr  ; 
      rdfs:comment  "{{description}}"@fr   ; 
      schema:image  "{{image}}" ; 
      schema:photoCredit  "{{photoCredit}}" ; 
      schema:status  "{{memberStatus}}"@fr . 
  }
}
