PREFIX schema: <http://schema.org/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

insert {
  graph <http://uda.ca> { 
    ?s rdfs:label ?label . 
  } 
} 
where { 
  graph <http://uda.ca> { 
    ?s schema:firstName ?first ;   
      schema:lastName ?last .      
    bind(concat(?first, " ", ?last) as ?label)
  } 
}