PREFIX schema: <http://schema.org/> 
PREFIX wd: <http://www.wikidata.org/entity/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

delete {
  graph <http://uda.ca> {
    ?s schema:status ?program
  }
}
insert {
  graph <http://uda.ca> { 
    ?s schema:memberOf  ?programClass .  
    ?programClass a schema:ProgramMembership ; 
      schema:host wd:Q3550100 ; 
      rdfs:label ?program . 
  }
}
where {  
  graph <http://uda.ca> {
    ?s schema:status ?program . 
    bind (URI(CONCAT("http://uda.ca/", str(?program))) as ?programClass)
  }
}